const {sections,emptyProfile,validateProfile,flatten}=AutumnSchema;
let profile=emptyProfile(),current='personal',dirty=false,toastTimer,profiles=[],activeProfileId='default';
const $=s=>document.querySelector(s);
function el(tag,attrs={},text){const x=document.createElement(tag);for(const [k,v]of Object.entries(attrs))x.setAttribute(k,v);if(text!=null)x.textContent=text;return x;}
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',5000);}
function changed(){dirty=true;$('#save-state').textContent='有未保存的修改';}
function renderNav(){const n=$('#nav');n.replaceChildren();for(const s of [...sections,{key:'import',label:'导入简历'},{key:'ai',label:'AI 接口设置'}]){const b=el('button',{class:s.key===current?'active':''},s.label);b.onclick=()=>{current=s.key;render();};n.append(b);}}
function render(){renderNav();const editor=$('#editor');editor.replaceChildren();if(current==='import')return renderImport(editor);if(current==='ai')return renderAI(editor);
 const s=sections.find(s=>s.key===current);const heading=el('div',{class:'section-title'});heading.append(el('h2',{},s.label));if(s.repeat){const add=el('button',{},'+ 添加一条');add.onclick=()=>{if(profile[s.key].length>=50)return toast('每类最多 50 条');profile[s.key].push({});changed();render();};heading.append(add);}editor.append(heading);
 const rows=s.repeat?profile[s.key]:[profile[s.key]];if(!rows.length){const empty=el('div',{class:'empty'});empty.append(el('h3',{},'把这段经历放进资料库'),el('p',{},'点击「添加一条」，每段经历单独保存，方便逐条填写。'));editor.append(empty);}
 rows.forEach((row,index)=>{const card=el('section',{class:'card'}),head=el('div',{class:'card-head'});head.append(el('h3',{},s.repeat?`${s.label} ${String(index+1).padStart(2,'0')}`:'基本资料'));if(s.repeat){const remove=el('button',{class:'danger'},'删除');remove.onclick=()=>{if(!confirm('删除这条经历？保存资料后生效。'))return;rows.splice(index,1);changed();render();};head.append(remove);}card.append(head);const grid=el('div',{class:'grid'});s.fields.forEach(f=>{const label=el('label',{class:f.type==='textarea'?'wide':''},f.label);const input=el(f.type==='textarea'?'textarea':'input',{type:['date','month'].includes(f.type)?'text':f.type,autocomplete:'off',placeholder:f.type==='month'?'YYYY-MM；至今可填“至今”':f.type==='date'?'YYYY-MM-DD（未知具体日期可留空）':''});input.value=row[f.key]||'';input.oninput=()=>{row[f.key]=input.value;changed();};label.append(input);grid.append(label);});card.append(grid);editor.append(card);});}
async function save(){try{profile=validateProfile(profile);const item=profiles.find(p=>p.id===activeProfileId);if(item)item.profile=structuredClone(profile);await chrome.storage.local.set({profile,profiles,activeProfileId});dirty=false;$('#save-state').textContent=`已保存 · ${flatten(profile).length} 项资料`;toast('资料已保存，可以去填写网申了');}catch(e){toast(e.message);}}
$('#save').onclick=save;
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,profile:validateProfile(profile)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a',{href:url,download:'秋填-简历备份.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出当前资料，不包含 API Key');};
function renderImport(editor){
 editor.append(el('h2',{},'导入简历'),el('p',{},'粘贴简历文字后，可通过你配置的 AI 提取为资料；提取结果需检查并保存。PDF / Word 请先复制正文到下方。'));
 const text=el('textarea',{placeholder:'粘贴你的完整简历正文…',rows:12,'aria-label':'简历正文'}),parse=el('button',{class:'primary'},'用 AI 提取资料');editor.append(text,el('p',{},'点击提取将把这段文字发送到你配置的 AI 接口。当前资料会在你应用预览后被替换。'),parse);
 const preview=el('div');editor.append(preview);
 parse.onclick=async()=>{if(!text.value.trim())return toast('请先粘贴简历');parse.disabled=true;parse.textContent='正在提取…';try{const schema=Object.fromEntries(sections.map(s=>[s.key,s.repeat?[Object.fromEntries(s.fields.map(f=>[f.key,f.label]))]:Object.fromEntries(s.fields.map(f=>[f.key,f.label]))]));const res=await chrome.runtime.sendMessage({type:'AI_PARSE',text:text.value,schema});if(!res.ok)throw Error(res.error);showPreview(validateProfile(res.profile),preview);}catch(e){toast(e.message);}finally{parse.disabled=false;parse.textContent='用 AI 提取资料';}};
 const details=el('details');details.open=true;details.append(el('summary',{},'从 JSON 备份导入（无需 AI）'));const file=el('input',{type:'file',accept:'.json,application/json','aria-label':'选择简历备份'});file.onchange=async()=>{try{if(file.files[0].size>2000000)throw Error('备份文件不能超过 2 MB');const p=JSON.parse(await file.files[0].text());showPreview(validateProfile(p.profile||p),preview);}catch(e){toast('导入失败：'+e.message);}};details.append(el('p',{},'选择秋填导出的 JSON 文件，预览后应用。导入不会直接保存。'),file);editor.append(details);
 const template=el('details'),code=el('pre');code.style.overflow='auto';template.append(el('summary',{},'查看 JSON 格式'),code);code.textContent=JSON.stringify(emptyProfile(),null,2);editor.append(template);
}
function showPreview(p,container){container.replaceChildren();container.append(el('h3',{},`导入预览 · ${flatten(p).length} 项`));const code=el('textarea',{class:'code','aria-label':'导入结果 JSON'});code.value=JSON.stringify(p,null,2);container.append(code);const apply=el('button',{class:'primary'},'应用预览，前往检查');apply.onclick=()=>{try{const next=validateProfile(JSON.parse(code.value));if(flatten(profile).length&&!confirm('用导入资料替换当前资料？你仍需点击保存才会写入。'))return;profile=next;current='personal';changed();render();toast('已应用，请检查各类经历并保存');}catch(e){toast(e.message);}};container.append(apply);}
async function renderAI(editor){
 editor.append(el('h2',{},'AI 接口设置'),el('p',{},'基础自动填写和点选辅助无需 AI。配置兼容 Chat Completions 的接口，可提取简历，并为未识别字段生成匹配建议。'));
 const card=el('div',{class:'card grid'});let c={};try{c=(await chrome.storage.local.get('aiConfig')).aiConfig||{};}catch{}if(current!=='ai')return;
 const inputs={};for(const [k,label,placeholder]of [['endpoint','完整接口地址','https://你的服务商/v1/chat/completions'],['model','模型名称','填写服务商提供的模型 ID'],['key','API Key','仅保存在当前浏览器']]){const l=el('label',{class:'wide'},label),input=el('input',{type:k==='key'?'password':'text',placeholder,autocomplete:'off'});input.value=c[k]||'';inputs[k]=input;l.append(input);card.append(l);}editor.append(card,el('p',{},'仅在点击 AI 操作时发送数据。简历提取发送正文；字段匹配发送网页字段标签和资料条目名称，不发送简历字段值。API Key 保存在扩展本地存储，不写入网页。'));
 const save=el('button',{class:'primary'},'保存并授权接口');save.onclick=async()=>{try{const config=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value.trim()]));const u=new URL(config.endpoint);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('请使用 HTTPS 地址，或本机 localhost / 127.0.0.1 地址');if(u.username||u.password)throw Error('请勿在 URL 中填写密码');if(!config.model||!config.key)throw Error('请填写模型名称和 API Key');const granted=await chrome.permissions.request({origins:[u.origin+'/*']});if(!granted)throw Error('未授予接口访问权限');await chrome.storage.local.set({aiConfig:config});toast('AI 设置已保存');}catch(e){toast(e.message);}};const clear=el('button',{},'清除 AI 设置');clear.onclick=async()=>{await chrome.storage.local.remove('aiConfig');render();toast('已清除接口和 API Key');};editor.append(save,document.createTextNode(' '),clear);
}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
function renderProfileSelect(){const select=$('#profile-select');select.replaceChildren();for(const p of profiles){const option=el('option',{value:p.id},p.name);option.selected=p.id===activeProfileId;select.append(option);}$('#profile-name').value=profiles.find(p=>p.id===activeProfileId)?.name||'';}
$('#profile-select').onchange=async e=>{const id=e.target.value;if(dirty&&!confirm('放弃未保存的修改并切换简历？')){renderProfileSelect();return;}try{const item=profiles.find(p=>p.id===id);profile=validateProfile(item.profile);activeProfileId=id;dirty=false;await chrome.storage.local.set({profile,activeProfileId});$('#save-state').textContent=`已切换 · ${item.name}`;renderProfileSelect();render();}catch(error){toast(error.message);}};
$('#new-profile').onclick=async()=>{if(dirty&&!confirm('放弃当前未保存的修改并新建简历？'))return;const name=$('#profile-name').value;if(!name?.trim())return toast('请先填写简历名称');if(profiles.length>=20)return toast('最多保存 20 份简历');const id=crypto.randomUUID();profiles.push({id,name:name.trim().slice(0,60),profile:emptyProfile()});activeProfileId=id;profile=emptyProfile();dirty=false;await chrome.storage.local.set({profile,profiles,activeProfileId});renderProfileSelect();render();toast('新简历已创建，请补充资料并保存');};
$('#rename-profile').onclick=async()=>{const item=profiles.find(p=>p.id===activeProfileId);const name=$('#profile-name').value;if(!name?.trim())return toast('请先填写新的简历名称');item.name=name.trim().slice(0,60);await chrome.storage.local.set({profiles});renderProfileSelect();};
(async()=>{try{const data=await chrome.storage.local.get(['profile','profiles','activeProfileId']);profile=validateProfile(data.profile||{});profiles=Array.isArray(data.profiles)&&data.profiles.length?data.profiles:[{id:'default',name:'我的第一份简历',profile}];activeProfileId=data.activeProfileId||profiles[0].id;if(!profiles.some(p=>p.id===activeProfileId))activeProfileId=profiles[0].id;$('#save-state').textContent=`已载入 · ${flatten(profile).length} 项资料`;}catch(e){toast(e.message);profiles=[{id:'default',name:'我的第一份简历',profile}];}renderProfileSelect();render();})();
