const assert=require('node:assert/strict');
require('../extension/schema.js');require('../extension/engine.js');
const S=globalThis.AutumnSchema,E=globalThis.AutumnEngine;
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
const p=S.validateProfile({personal:{name:'测试同学',phone:'13800000000',email:'demo@example.com'},education:[{school:'示例大学',start:'2022-09',end:'2026-06'}],work:[{company:'甲公司',description:'开发'}],internship:[{company:'乙公司',description:'研究'}],project:[{name:'甲项目',role:'前端',start:'2024-02'},{name:'乙项目',role:'后端',start:'2025-01'}]});const entries=S.flatten(p);
test('手机号别名匹配',()=>assert.equal(E.choose({labels:['* 手机号：'],section:'personal',index:null},entries).value,'13800000000'));
test('无上下文描述不猜测',()=>assert.equal(E.choose({labels:['描述'],section:null,index:null},entries),null));
test('多段项目没有索引时不猜测',()=>assert.equal(E.choose({labels:['项目名称'],section:'project',index:null},entries),null));
test('第二段经历索引',()=>assert.equal(E.choose({labels:['项目名称'],section:'project',index:1},entries).value,'乙项目'));
test('实习和工作分开',()=>assert.equal(E.choose({labels:['公司名称'],section:'internship',index:0},entries).value,'乙公司'));
test('不存在的经历不套用第一条',()=>assert.equal(E.choose({labels:['学校名称'],section:'education',index:1},entries),null));
test('未知字段不猜测',()=>assert.equal(E.choose({labels:['紧急联系人姓名'],section:null,index:null},entries),null));
test('出生日期不会生成未知日',()=>assert.equal(E.dateValue('2003-08','date'),null));
test('完整日期转月份',()=>assert.equal(E.dateValue('2026-6-01','month'),'2026-06'));
test('日期规范化',()=>assert.equal(E.dateValue('2026年6月1日','date'),'2026-06-01'));
test('无效日期拒绝',()=>assert.equal(E.dateValue('2025-02-29','date'),null));
test('闰年日期接受',()=>assert.equal(E.dateValue('2024-02-29','date'),'2024-02-29'));
test('至今不伪造日期',()=>assert.equal(E.dateValue('至今','date'),null));
test('未知字段不进入资料',()=>assert.equal(S.validateProfile({personal:{name:'甲',secret:'乙'}}).personal.secret,undefined));
test('拒绝畸形重复经历',()=>assert.throws(()=>S.validateProfile({project:{name:'甲'}})));
test('拒绝对象值',()=>assert.throws(()=>S.validateProfile({personal:{name:{x:1}}})));
const identity=S.flatten(S.validateProfile({personal:{idType:'身份证',idNumber:'11010120000101001X'}}));
for(const label of ['证件号码','身份证','身份证号','身份证号码','证件号','居民身份证号码','公民身份号码','身份证件号码','请输入身份证号码'])test('身份证号码匹配：'+label,()=>assert.equal(E.choose({labels:[label],section:'personal'},identity)?.id,'personal.0.idNumber'));
test('证件类型不混入身份证号码',()=>assert.equal(E.choose({labels:['证件类型'],section:'personal'},identity)?.id,'personal.0.idType'));
test('家属证件不套用本人号码',()=>assert.equal(E.choose({labels:['证件号码'],section:'family'},identity),null));
test('智联必填家庭关系标题',()=>assert.equal(E.sectionKey('家庭关系 必填',S.sections),'family'));
test('标题必填标记和星号',()=>assert.equal(E.sectionKey('* 家庭关系（必填）',S.sections),'family'));
test('亲属任职声明不归入家庭关系',()=>assert.equal(E.sectionKey('亲属在邮储银行体系任职情况',S.sections),null));
const relatives=S.flatten(S.validateProfile({personal:{name:'本人'},family:[{name:'母亲资料',relation:'母亲',role:'母亲职务',age:'48'},{name:'父亲资料',relation:'父亲',role:'父亲职位',age:'50'}]}));
test('姓名-父亲按关系匹配，不按数组序号',()=>assert.equal(E.choose({labels:['* 姓名-父亲'],section:'family',index:0},relatives)?.value,'父亲资料'));
test('姓名-母亲按关系匹配',()=>assert.equal(E.choose({labels:['姓名-母亲'],section:'family',index:0},relatives)?.value,'母亲资料'));
test('职位-父亲映射职务字段',()=>assert.equal(E.choose({labels:['职位-父亲'],section:'family'},relatives)?.value,'父亲职位'));
test('年龄-母亲只使用保存年龄',()=>assert.equal(E.choose({labels:['年龄-母亲'],section:'family'},relatives)?.value,'48'));
test('任职情况不根据工作单位推断',()=>assert.equal(E.choose({labels:['父亲是否为邮储银行体系内单位员工'],section:'family'},relatives),null));
test('缺少父亲资料时不套用母亲',()=>assert.equal(E.choose({labels:['姓名-父亲'],section:'family'},relatives.filter(f=>f.index!==1)),null));
test('两位父亲记录不猜测',()=>{const fields=[...relatives,...relatives.filter(f=>f.section==='family'&&f.index===1).map(f=>({...f,index:2,id:f.id.replace('.1.','.2.')}))];assert.equal(E.choose({labels:['姓名-父亲'],section:'family'},fields),null);});
console.log(`${count} tests passed`);
